### ISSUE TITLE
wscat command doesn't work

### ISSUE THREAD

**Issue by LuigiFrattolillo** [dickeyxxx/mean-sample#12]
After running 
wscat -c ws://localhost:3000
i receive the following message:

-bash: wscat: command not found

I've installed ws module locally and  globally, but it doesn't recognize the command!

**Comment by scarrick68** [comment]
edwallitt is right. I did sudo npm install --save wscat and it installed a package, but still didn't work. You need to sudo npm install -g wscat.

**Comment by dickeyxxx** [comment]
you should fix your box such that you don't have to use sudo

**Comment by scarrick68** [comment]
Thanks for the tip. I thougt this book was pretty good and really helped me
get a better understanding of how all the pieces in the stack work together
as well as how to streamline my dev environment. one suggestion I would
make is to put a link to the corresponding github page at the beginning of
each chapter. I had a way easier time following along once I was using your
repo with the book. It also gets a little disjoint starting in chapter 7.
Beginners aren't gonna know to do anything you don't explicitly tell them
and I noticed code in the github pages that wasn't mentioned in the book.
You should make it really clear when you do something that isn't explicitly
shown in the book. There are a few times when you give options or mention
other possibilities, but don't state which one is gonna be used going
forward and then some code i've never seen just appears in the repo.

**Comment by mark-leone** [comment]
I installed ws globally and locally on two different CentOS systems and an OSX system. In each instance it does not install the wscat binary anywhere. I looked specifically in the global node_modules installation directory, and the local node_modules installation directory, and I did a global search. The wscat binary is nowhere.

**Comment by dickeyxxx** [comment]
npm should install it like this: https://docs.npmjs.com/files/package.json#bin

nothing looks misconfigured in the wscat package.json

**Comment by mark-leone** [comment]
Well there's the problem. I was doing npm install ws, because this site (https://einaros.github.io/ws/) says that you install ws and it includes the executable wscat, or at least that's the way it reads to me. I didn't notice that on this thread people were saying to install wscat, until I saw you referencing the wscat package.json.

So now it works. Thanks

**Comment by ghcpc10** [comment]
i think if u r following the book, it says npm install --global ws, then when you run wscat, it wont understand what it is.
you should install wscat instead.

**Comment by tjunghans** [comment]
@mark-leone Thanks for the tip. I was having the same issue wondering what I was missing. The documentation on http://websockets.github.io/ws/ is still outdated.

**Comment by interglobalmedia** [comment]
For anyone who is interested, I had the same problem, but figured out a very simple solution. I did a local install of wscat, and then used the following command: node_modules/.bin/wscat -c ws://localhost:3001 in order to connect to my WebSockets server. Works beautifully. In other words, even though it states on the wscat page on npmjs.com that it is necessary to install it globally, it is NOT. Hope this helps!

**Comment by edujose35** [comment]
> For anyone who is interested, I had the same problem, but figured out a very simple solution. I did a local install of wscat, and then used the following command: node_modules/.bin/wscat -c ws://localhost:3001 in order to connect to my WebSockets server. Works beautifully. In other words, even though it states on the wscat page on npmjs.com that it is necessary to install it globally, it is NOT. Hope this helps! FYI, this was not for the mean sample, but it still should apply across the board.

This worked for me
